In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('03Narrativedata.csv',index_col=0) #原数据第1列有索引，index_col=0把第1列作为索引，而不是特征
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       889 non-null    float64
 1   Sex       889 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  889 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.7+ KB


### 一、处理分类型特征：编码与哑变量

将文字型数据转换为数值型。

1.**sklearn.preprocessing.LabelEncoder**：能够将分类**标签**转换为分类数值

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
y = data.iloc[:,-1] #要输入的是标签，不是特征矩阵，所以允许一维

In [6]:
le = LabelEncoder() #实例化
le = le.fit(y) #导入数据
label = le.transform(y) #transform接口调取结果
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2,

In [7]:
le.classes_ #以下标签分别替换为0、1、2

array(['No', 'Unknown', 'Yes'], dtype=object)

In [8]:
le.fit_transform(y) #后两步一步到位

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2,

In [9]:
le.inverse_transform(label) #使用inverse_transform可以逆转

array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'Unknown', 'Yes', 'No', 'No', 'No', 'Unknown', 'No', 'Yes', 'No',
       'Yes', 'Unknown', 'Yes', 'Yes', 'Yes', 'No', 'Unknown', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Unknown', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'Unknown', 'No', 'Unknown',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Unknown', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'Unknown', 'No', 'No', 'Yes', 'No', 'No', 'Ye

In [10]:
data.iloc[:,-1] = label #让标签等于运行出来的结果

In [11]:
data.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

如果不需要教学展示会这么写：<br>
data.iloc[:,-1] = LabelEncoder().fit_transform(data.iloc[:-1])

2.**sklearn.preprocessing.OrdinalEncoder**：能够将分类**特征**（有序变量）转换为分类数值

In [12]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
data_ = data.copy()
data_.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [14]:
X = data_.iloc[:,1:-1]

In [15]:
fe = OrdinalEncoder() #实例化
fe = fe.fit(X) #导入数据
features = fe.transform(X) #transform接口调取结果
features

array([[1., 2.],
       [0., 0.],
       [0., 2.],
       ...,
       [0., 2.],
       [1., 0.],
       [1., 1.]])

In [16]:
fe.categories_ #类似classes_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [17]:
data_.iloc[:,1:-1] = features
data_.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

如果不需要教学展示会这么写：<br>
data.iloc[:,1:-1] = OrdinalEncoder().fit_transform(data.iloc[:,1:-1])

注意，**性别**和**舱门**是**名义变量**（各取值之间相互独立，彼此之间完全没有联系），这种处理方式在算法看来，是连续且可以计算的，事实上并非如此，因此要使用`OneHotEncoder`哑变量的方式来处理。对于**学历**这种**有序变量**可以使用`OrdinalEncoder`来处理。

`OrdinalEncoder`：["S","Q","C"]→[0,1,2]<br>
`OneHotEncoder`：["S","Q","C"]→[[1,0,0],[0,1,0],[0,0,1]]

3.**sklearn.preprocessing.OneHotEncoder**：能够将分类**特征**（名义变量）转换为分类数值

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
X = data.iloc[:,1:-1]
X.head()

Sex Embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

In [20]:
enc = OneHotEncoder(categories='auto').fit(X)
result = enc.transform(X).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

result = OneHotEncoder(categories='auto').fit_transform(X).toarray()

In [21]:
enc.get_feature_names() #每个哑变量的类别

array(['x0_female', 'x0_male', 'x1_C', 'x1_Q', 'x1_S'], dtype=object)

In [22]:
#依然可以还原
pd.DataFrame(enc.inverse_transform(result))

0  1
0      male  S
1    female  C
2    female  S
3    female  S
4      male  S
..      ... ..
884    male  S
885  female  S
886  female  S
887    male  C
888    male  Q

[889 rows x 2 columns]

In [23]:
#将两个表左右相连
newdata = pd.concat([data,pd.DataFrame(result)],axis=1)
newdata

Age     Sex Embarked  Survived    0    1    2    3    4
0    22.0    male        S       0.0  0.0  1.0  0.0  0.0  1.0
1    38.0  female        C       2.0  1.0  0.0  1.0  0.0  0.0
2    26.0  female        S       2.0  1.0  0.0  0.0  0.0  1.0
3    35.0  female        S       2.0  1.0  0.0  0.0  0.0  1.0
4    35.0    male        S       0.0  0.0  1.0  0.0  0.0  1.0
..    ...     ...      ...       ...  ...  ...  ...  ...  ...
886  27.0    male        S       0.0  1.0  0.0  0.0  0.0  1.0
887  19.0  female        S       2.0  0.0  1.0  1.0  0.0  0.0
888  28.0  female        S       0.0  0.0  1.0  0.0  1.0  0.0
889  26.0    male        C       1.0  NaN  NaN  NaN  NaN  NaN
890  32.0    male        Q       0.0  NaN  NaN  NaN  NaN  NaN

[891 rows x 9 columns]

In [24]:
#删除Sex和Embarked列，并覆盖原数据
newdata.drop(["Sex","Embarked"],axis=1,inplace=True)

In [25]:
newdata.head()

Age  Survived    0    1    2    3    4
0  22.0       0.0  0.0  1.0  0.0  0.0  1.0
1  38.0       2.0  1.0  0.0  1.0  0.0  0.0
2  26.0       2.0  1.0  0.0  0.0  0.0  1.0
3  35.0       2.0  1.0  0.0  0.0  0.0  1.0
4  35.0       0.0  0.0  1.0  0.0  0.0  1.0

In [26]:
#改列索引
newdata.columns = ['Age','Survived','Female','Male','Embarked_C','Embarked_Q','Embarked_S']
newdata.head()

Age  Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
0  22.0       0.0     0.0   1.0         0.0         0.0         1.0
1  38.0       2.0     1.0   0.0         1.0         0.0         0.0
2  26.0       2.0     1.0   0.0         0.0         0.0         1.0
3  35.0       2.0     1.0   0.0         0.0         0.0         1.0
4  35.0       0.0     0.0   1.0         0.0         0.0         1.0

4.**sklearn.preprocessing.LabelBinarizer**：标签做哑变量不常见。

**5.总结。**

编码与哑变量|功能|重要参数|重要属性|重要接口
-|-|-|-|-
.LabelEncoder|分类标签编码|N/A|.classes_：查看标签中有多少类别|fit,<br>transform,<br>fit_transform,<br>inverse_transform
.OrdinalEncoder|分类特征编码|N/A|.categories_：查看特征中有多少类别|fit,<br>transform,<br>fit_transform,<br>inverse_transform
.OneHotEncoder|独热编码，为名义变量创建哑变量|categories='auto'算法自己判断每个特征有哪些类别|.categories_：查看特征中有多少类别|fit,<br>transform,<br>fit_transform,<br>inverse_transform,<br>get_feature_names

### 二、处理连续型数据：二值化与分段

1.**sklearn.preprocessing.Binarizer**：二值化

根据阈值将数据二值化，用于处理连续型变量。大于阈值的值映射为1，小于或等于阈值的值映射为0。

（1）年龄二值化：阈值30

In [27]:
from sklearn.preprocessing import Binarizer

In [28]:
data_2 = data.copy()
X = data_2.iloc[:,0].values.reshape(-1,1) #类为特征专用，所以不能使用一维数组

In [29]:
transformer = Binarizer(threshold=30).fit_transform(X) #三步一步到位，大于等于30岁用1替换
transformer

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],

In [30]:
data_2.iloc[:,0] = transformer
data_2.head()

Age     Sex Embarked  Survived
0  0.0    male        S         0
1  1.0  female        C         2
2  0.0  female        S         2
3  1.0  female        S         2
4  1.0    male        S         0

（2）标签二值化：阈值1，即unknown和死亡都用死亡替换

2.**sklearn.preprocessing.KBinsDiscretizer**分箱：将连续型变量划分为分类变量，将连续型变量排序后按顺序分箱后编码。

In [31]:
from sklearn.preprocessing import KBinsDiscretizer

In [32]:
X = data.iloc[:,0].values.reshape(-1,1)

In [33]:
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform') #实例化，每一列是一个特征
est.fit_transform(X) #后两步合一步

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],

In [34]:
#查看转换后分的箱：变成了一列中的三箱
set(est.fit_transform(X).ravel()) #降成一维放在集合中

{0.0, 1.0, 2.0}

In [35]:
est = KBinsDiscretizer(n_bins=3, encode='onehot', strategy='uniform') #实例化，每一列是一个特征中的一个类别

In [36]:
#查看转换后分的箱：变成了哑变量
est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])